### ISSUE TITLE
Number of Likes required impossible to satisfy

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#129] opened 2024-11-26 21:22 UTC
Right now, we require about 50% (variable) of likes based on the number of justifications presented to the student. 
There have been reports of students not getting enough justifications to be able to provide the number of likes expected.

**Comment by profgrumpy** [comment] 2024-11-26 21:27
Adding this feedback to the above (from TA): 
For some students, who were unable to finish step 1 while the others finished step 2, I reopened step 1 for them after all others finished their step 2. They were able to do step 1 correctly, however, when I opened the second step, the program was requiring more minimum likes to be given than the number of justifications present for them to choose from.

**Comment by dvitel** [comment] 2024-12-08 01:18
Connected to #131 and #134 But we discussed also the idea to have at minimum number of likes equal to the number of question alternatives for which there is non-empty set of justifications. I will test again the described by TA scenario

**Comment by dvitel** [comment] 2024-12-08 03:20
After testing I was not able to reproduce, seems it was also fixed with #131

**Closed by dvitel** 2024-12-08 03:20 UTC
Labels: bug
