### ISSUE TITLE
Quiz-grader's DataTable is not able to sort some columns

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#64] opened 2022-05-10 00:50 UTC
In quiz-grader, unable to sort the total (%) and total score columns. These two last columns do not allow to sort the DataTable's rows based on their values.
Clicking the columns' headers has no effect but the up/down arrows icons are changing, as expected.

Similarly, the "likes received" and "justifications" columns are not sorting their values properly either. This may be due to many of the values being 0 and possibly still at their default value as of the initialization of the tables.

**Comment by profgrumpy** [comment] 2022-05-11 11:27
At this point, it's possible the table update mechanism needs to be replaced by something in the lines of:
https://datatables.net/forums/discussion/67415/dynamic-datatable-populate-from-a-fetch-api

**Comment by drpventura** [comment] 2022-05-16 17:38
It appears that the problem is that there are no values in either the Total Score and Total % fields.

**Comment by profgrumpy** [comment] 2022-05-16 18:53
They are populated dynamically; the page takes a long time to load when trying to first gather all data on server side so it is served without these columns quickly and the wide blue button above the table allows you to get an update on these column after potentially changing around the values of the weights that you fixed recently

**Comment by profgrumpy** [comment] 2022-05-16 18:54
I am thinking the JS datatables plugin is not aware that the values were injected in the innerHTML of the fields in the table. I tried redrawing the table without success after the update was done.

**Comment by profgrumpy** [comment] 2022-05-19 11:41
As of this morning, the following columns seem to have the same problem; 
- [ ] Likes received
- [ ] Justification

We discussed that, given the fact that the loading speed of the page is more than acceptable now, we might want to no longer inject the data in the inner HTML of the columns asynchronously but, instead, reload the page when recomputing all grades.

**Comment by drpventura** [comment] 2022-05-23 19:17
After trying adding column options, both num and html-num, those cause no sorting to happen on the fields.

https://github.com/cereal-lab/EvoPIE/blob/faca5c8e7c9a667c5706e13e641d28dd9ccca173/evopie/templates/quiz-grader.html#L51-L60

Going to try adding the data-order attribute per https://datatables.net/manual/data/orthogonal-data#HTML-5

**Comment by drpventura** [comment] 2022-05-23 20:13
data-order attributes per  https://datatables.net/manual/data/orthogonal-data#HTML-5 has fixed the issue. 
Merged into master

**Closed by drpventura** 2022-05-23 20:13 UTC
Labels: bug
