### ISSUE TITLE
Justifications Assignment Policy

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#53] opened 2022-05-01 10:36 UTC
- [ ] We need to ensure a fair exposure for all justifications so that students have a fair chance to get their justifications liked
- [ ] On top of that, we can track the "reputation" or "karma" of any given student by maintaining stats on the likes they received for their justifications in a given quiz or maybe even across all quizzes / courses
- [ ] Use this karma metric to guarantee that each student gets to view a certain percentage of expectedly good justifications in addition to a sample ensuring fairness of representation for all authors

**Comment by dvitel** [comment] 2022-05-11 00:14
Created branch, committed small changes of refactoring. See https://github.com/cereal-lab/EvoPIE/commit/d592e725a2b494884e58aea19082f8fc48a635c0

The problem is that method get_student (which calls getJustifications) reexecutes on page refresh and tend to trigger policy several times. Somehow we need to protect justification.seen stats from this behavior and show justifications for same student deterministically. Possibly with another db table. This is to discuss.

**Comment by profgrumpy** [comment] 2022-05-11 07:36
The model Attempt capture a submission from the student, we could extend it to link, via another table, to the justifications being seen.

**Comment by profgrumpy** [comment] 2022-05-12 06:17
As you work on this, could you also update the doc at https://github.com/cereal-lab/EvoPIE/wiki/Justification-Dispatching-Policy

**Comment by dvitel** [comment] 2022-05-12 20:17
first small step - commit https://github.com/cereal-lab/EvoPIE/commit/1133e5233a628417bdeb46056021ef5781adb14b
Simple policies and policy builders are declared there:
https://github.com/cereal-lab/EvoPIE/blob/1133e5233a628417bdeb46056021ef5781adb14b/evopie/routes_pages.py#L352-L392

I experimented with next simple fair policy:
https://github.com/cereal-lab/EvoPIE/blob/1133e5233a628417bdeb46056021ef5781adb14b/evopie/routes_pages.py#L497-L505

the idea here that first we ensure that each justification was given at least once and then we ensure that that each of them 2 times was given, then random.
Checked on tests and got results that confirm that all justifications were shown at least twice:
```
sqlite> select min(seen), avg(seen), max(seen)  from justification;
2|3.0|6
```

**Comment by dvitel** [comment] 2022-05-13 04:40
https://github.com/cereal-lab/EvoPIE/commit/141e1c3c654b11f62cd52fe83009344b8d4b8992
New policy builders added: tournament, fitness_proportional, softmax, epsilon_greedy.
interval_estimation was not implemented - we need  to discuss fitness based policies one more time.
get_justification_distribution endpoint was added to check quality of policy visually.
Endpoint returns image/png. Here is the example for committed strategy (from previous comment)
![h](https://user-images.githubusercontent.com/8459523/168211955-8028961a-eb87-47ab-8756-a295bfe16b2c.png)
Endpoint url is /quiz/<quiz_id>/justification/histogram
Note about this histogram - justifications are sorted from left to right according to their fitness which correspond to initial score of student which produce the justification. Better attempt lead to better justification fitness - but this is subject for discussion. 
Y axis - number, how many times this justification was given to students, X axis - one bar per justification which are sorted according to defined fitness. This picture basically shows that given policy does not prefer justification from better performing student.

**Comment by dvitel** [comment] 2022-05-13 05:00
![h](https://user-images.githubusercontent.com/8459523/168214110-d8e94563-0da8-4869-b196-18ec99aa8cbd.png)
This is a bit updated same histogram with fitness labels specified for X axis - numbers represent number of correct answers on first attempt

**Comment by dvitel** [comment] 2022-05-13 05:31
![h2](https://user-images.githubusercontent.com/8459523/168217287-c0c83f2b-6dfa-43b6-a47f-24c193231f5d.png)
This is histogram for next policy (tournament of 7 after all seen):
```python
  selected_justification_map = select_justifications(possible_justifications, q.num_justifications_shown, \
      selection_policy = \
          not_seen_justification_and(not_seen_n_times=1, \
              not_seen_policy = select_random_justification, \
              fallback_policy = tournament(7, fitness=get_justification_fitness)))                    
```

**Comment by dvitel** [comment] 2022-05-13 05:35
![h3](https://user-images.githubusercontent.com/8459523/168217806-93a310c3-4326-4ff3-9bbd-542d50d67129.png)
for epsilon-greedy 25%
```python
  selected_justification_map = select_justifications(possible_justifications, q.num_justifications_shown, \
      selection_policy = \
          not_seen_justification_and(not_seen_n_times=1, \
              not_seen_policy = select_random_justification, \
              fallback_policy = epsilon_greedy(0.25, \
                  best_policy=select_random_justification, \
                  fallback_policy=select_random_justification, \
                  fitness=get_justification_fitness)))
```

**Comment by dvitel** [comment] 2022-05-13 16:49
https://github.com/cereal-lab/EvoPIE/commit/d24c696dcc06cd31a356eeb67e889026782775e9
We are going to select one concrete policy to for further experiments.
We consider policies in a form:
```python
  selected_justification_map = select_justifications(possible_justifications, q.num_justifications_shown, \
      selection_policy = j_slot_group_till(num_in_group,\
          in_group_policy=j_least_seen(j_random), \
          out_group_policy=SUBPOLICY))
```
In next discussion I ran disbursement for cases when 1 of 3 slots (1/3) and 2 of 3 slots (2/3) where dedicated for least_seen. We need to pick SUBPOLICY to be one of the following (result distributions for 1/3 and 2/3 are provided):
1. SUBPOLICY = Tournament of 7.
1/3
![slots-1-of-3-tournament-7](https://user-images.githubusercontent.com/8459523/168329586-827d579c-c4a5-41e1-8d95-8dbb002886ac.png)
2/3
![slots-2-of-3-tournament-7](https://user-images.githubusercontent.com/8459523/168329613-adb04f66-4606-47c0-80e3-1a8651dfaf33.png)
--------------------------------------------------

2. SUBPOLICY = Epsilon Greedy with 20% of taking best
1/3
![slots-1-of-3-e-greedy-20](https://user-images.githubusercontent.com/8459523/168329699-d986763b-b501-430b-95ac-2f2e8908613e.png)
2/3
![slots-2-of-3-e-greedy-20](https://user-images.githubusercontent.com/8459523/168329775-ab51c4c9-2856-4515-99e8-53b1f2ceca10.png)
--------------------------------------------------

3. SUBPOLICY = Fitness proportional
1/3
![slots-1-of-3-fitness-prop](https://user-images.githubusercontent.com/8459523/168330211-03c16e9b-2e6e-45fd-812c-706c67f19c8a.png)
2/3
![slots-2-of-3-fitness-prop](https://user-images.githubusercontent.com/8459523/168330286-fa33507e-9e89-4c7b-bad2-9421d1aa928f.png)

**Comment by dvitel** [comment] 2022-05-13 16:58
We leave for later considerations:
1. Adding likes to fitness of justification (dynamic part of  fitness). Currently only step 1 performance of student is used (base fitness)
2. Considering adding complexity of justification itself to fitness (for example length of justification or other characteristics)
4. Considerations about metric: which policy is better and which is not. Probably could be measured on student simulation with tests. Here we need to consider behaviors of students in simulation I assume. 
5. Justifications that distract students (for correct answers but with many likes)

**Comment by profgrumpy** [comment] 2022-05-14 00:14
ping on the previous request to update the doc 
https://github.com/cereal-lab/EvoPIE/wiki/Justification-Dispatching-Policies

**Comment by profgrumpy** [comment] 2022-05-14 00:46
I would start with k-tournament but the parameter (7) is maybe something that we should express as a % of the population size. 7 out of 7 is elitism. 7 out of 10,000 is not much pressure at all. See what I mean?

**Comment by profgrumpy** [comment] 2022-05-14 00:49
Another suggestion: we talked about putting these parameters in a global object. I have not used a config object for flask to hold data like the secret key and the likes. @drpventura I'm assuming this is a "best practice" with flask. Should we use this approach and add to that config object things such as the max number of justifications shown to students in step 2 per alternative, along with the % of it that is to be dedicated to fairness?
@dvitel  Do you seen the need for other parameters based on what your code needs?

**Comment by dvitel** [comment] 2022-05-14 17:59
> ping on the previous request to update the doc https://github.com/cereal-lab/EvoPIE/wiki/Justification-Dispatching-Policies

Updated

**Comment by dvitel** [comment] 2022-05-14 18:04
> I would start with k-tournament but the parameter (7) is maybe something that we should express as a % of the population size. 7 out of 7 is elitism. 7 out of 10,000 is not much pressure at all. See what I mean?

We should express tournament size in % because of the fact that population of justifications does not have fixed size. Policy executes for each (question_id, option_id) and for different options there could be different number of possible justifications.

> @dvitel Do you seen the need for other parameters based on what your code needs?
For now it is number of slots for lest_seen policy and size of tournament. But in case if we use some other policies - other parameters could appear. Num_slots is defined in Quiz table. I just mention the idea to preserve options in Quiz table json column for ease to reconfigure (but you probably will say no).

**Comment by profgrumpy** [comment] 2022-05-14 23:54
I think right now all these parameters are hardcoded, the suggestion I made last time was to simply move them to a configuration object after checking with @drpventura whether this is something that we could merge with the flask config object. If this is still on the table for discussion, let's chat monday with Phil and see how easy / feasible it is as a first step. 
We can then move things to the Quiz model, if we realize that we want different behaviors on a per-quiz basis; e.g., quiz #1 is traditional, quiz#2 is evolving the distractors, quiz #3 is traditional but with a different justification selection policy. The main issue is whether we make all these options available to everyone (potentially overwhelming) or separate them. A "researcher" role is no good since we would have to coordinate tightly the release of each quiz. It just seems easier to configure the software for all users and let them configure their quiz w/r to pedagogical features. If need be to experiment with a different setup, again, all users should be experiencing the same thing. Does this make sense?

**Closed** 2022-05-21 04:41 UTC
Labels: New Feature
